version: '2.1'

services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code
    volumes:
      - ./code:/code
    # https://docs.docker.com/compose/compose-file/compose-file-v2/#security_opt
    security_opt:
      - seccomp:unconfined
